routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/register', function (){
    return redirect('/login');
});

Route::get('/', function (){
    return redirect('/login');
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', function (){
        return redirect('/task');
    });

    Route::get('home', function (){
        return redirect('/task');
    });

    Route::resource('task','TaskController');

    Route::resource('comment','CommentController');

    Route::resource('media','MediaController');

    Route::delete('mediaDeleteByTask','MediaController@mediaDeleteByTask');

    Route::post('change-status', 'TaskController@changeStatus');

    Route::post('changeTodoStatus', 'TaskController@changeTodoStatus');

//    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('getServiceTeams/{id}', 'ServiceController@getServiceTeams');
    Route::get('show-team-serviecs', 'ServiceController@showTeamAndServices');
    Route::get('deleteTeamServices/{id}', 'ServiceController@deleteTeamServices');
    Route::get('deleteServices/{id}', 'ServiceController@destroy');

    Route::post('storeTeamsServices', 'ServiceController@storeTeamsServices')->name('storeTeamsServices');
    //------------------------------service
    Route::get('addservices','ServiceController@index');
    Route::resource('service',"ServiceController");
//    Route::post('service/{id}','ServiceController@destroy');

//------------------Organization------------------------
    Route::resource('organization','OrganizationController');

    Route::put('organizations/{id}','OrganizationController@update');

    Route::post('delorganization/{id}','OrganizationController@destroy');

    Route::get('getorganization/{id}','OrganizationController@show');
//-----------------------------------------------------------

//------------------Department
    Route::post('department','DepartmentController@store')->name('department');

    Route::post('department/{id}','DepartmentController@destroy');

    Route::get('getdepartment/{id}','DepartmentController@show');

    Route::put('updatedepartment/{id}','DepartmentController@update');

//-------------------------------------------------------------

//------------------Team--------------
    Route::resource('team','TeamController');

    Route::post('delteam/{id}','TeamController@destroy');

    Route::get('getAgentDetail/{id}','TeamController@show');

    Route::put('updateteam/{id}','TeamController@update');

//------------------teamMember
    Route::resource('teamMember','TeamMemberController');

    Route::post('delteammember/{id}','TeamMemberController@destroy');

    Route::get('teamMember/{id}','TeamMemberController@show');

    Route::put('teamMembers/{id}','TeamMemberController@update');

    Route::get('getodep/{id}','DepartmentController@getodep');

    Route::get('getTeamMember/{id}','TeamMemberController@index')->name('getTeamMember');
//-------------------------------------------------------------


    Route::resource('users', 'UserController')->middleware('isAdmin');

    Route::resource('roles', 'RoleController')->middleware('isAdmin');

    Route::resource('permissions', 'PermissionController')->middleware('isAdmin');

//------------------Task Manager
    Route::get('services', function () {
        return view('admin.services.index');
    });

    Route::get('account-manager', function () {
        return view('admin.task-management.account-manager-task-detail');
    });

    Route::resource('type','TypeController');

});

app/TeamMember.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TeamMember extends Model
{
    protected $table = 'team_members';

    protected $guarded = [];

    public function team()
    {
        return $this->belongsTo('App\Team');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function task()
    {
        return $this->belongsTo('App\Task');
    }
    public function medias()
    {
        return $this->hasMany('App\Media');
    }
    //Which tasks this teamMember to others
    public function assignTasks($count = null){
        $result = $this->hasMany('App\TaskRoute', 'assign_by');
        if(!is_null($count)){
            return $result->count();
        }
        return $result;
    }
    //Which task assigned to this teamMember
    public function assignedTasks($count = null){
        $result =  $this->hasMany('App\TaskRoute', 'assign_to');
        if(!is_null($count)){
            return $result->count();
        }
        return $result;
    }

    public function taskAssignByMe($taskID = null){
        if(!is_null($taskID)){
            return $this->hasMany('App\TaskRoute', 'assign_by')->where('task_id',$taskID)->first();
        }
        return null;
    }

    public function taskAssignToMe($taskID = null){
        if(!is_null($taskID)){
            return $this->hasMany('App\TaskRoute', 'assign_to')->where('task_id',$taskID)->first();
        }
        return null;
    }

}

app/Http/Controllers/TeamMemberController.php
<?php

namespace App\Http\Controllers;

use App\Organization;
use App\Team;
use App\TeamMember;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Spatie\Permission\Models\Role;

class TeamMemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id){
        $user = Auth::user();
        if($user->hasRole('Admin')){
            //Getting Specific Team
            $agents = Team::find($id);
            $teams = Team::whereId($id)->first();
        }else{
            //Getting Logged in user team
            $agents = $user->teamMember->team;
            $teams = Team::whereId($user->teamMember->team->id)->first();
        }


        if(is_null($agents)){
            toastr()->error('Team not exist!');
            return back();
        }
        $agents = $agents->teamMembers;

        $roles = Role::where('name','!=', 'Admin')->get();

        return view('admin.teamMember.list',compact('agents','teams','roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $auth = Auth::user();
//
//        if(!$auth->hasRole('Add Team Member')){
//            toastr()->warning('No permission!');
//            return back();
//        }

        $alreadyExist = User::where('email',$request['email'])->first();
        if(!is_null($alreadyExist)){
            toastr()->error('Email already exist!');
            return back();
        }

        $userInput = $request->except('team_id');
//        $password = str_random(6);
//        $userInput['password'] = bcrypt($password);
        $user = User::create($userInput);

        $team_member = TeamMember::create([
            'team_id' => $request['team_id'],
        ]);

//        'account_manager' => $request->keys('account_manager') ? $request->account_manager : 0
        $team_member->user()->associate($user)->save();

        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {

            foreach ($roles as $role) {
                $role_r = Role::where('id', '=', $role)->firstOrFail();
                $user->assignRole($role_r); //Assigning role to user
            }
        }

        toastr()->success('Data has been Added successfully!');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TeamMember  $teamMember
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $agent = TeamMember::findorfail($id);

        $output = array(
            'id' => $agent->id,
            'name' => $agent->name,
            'email' => $agent->email,
            'skype' => $agent->skype,
            'mobile' => $agent->mobile,
            'department_id' => $agent->department_id
        );
        return response()->json($output);

        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TeamMember  $teamMember
     * @return \Illuminate\Http\Response
     */
    public function edit(TeamMember $teamMember)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TeamMember  $teamMember
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $user = Auth::user();
        if(!$user->has('Edit Team Member')){
            toastr()->warning('No permission!');
            return back();
        }
        TeamMember::findorfail($id)->update($request->all());
        return View('admin.organization.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TeamMember  $teamMember
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $teamMember = TeamMember::find($id);
        $teamMember->user()->delete();
        $teamMember->delete();
        return back();
    }
}

resources/views/admin/teamMember/list.blade.php
@extends('admin.layouts.app')

@section('content')
<style>
    input{
        position: relative !important;
        right: auto !important;
    }
</style>
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row">
                    <div class="col-sm-6">
                        <h2><a href="{{ url()->previous() }}" class="btn btn-xs btn-link"><i
                                        class="fa fa-arrow-left"></i></a>Team Members</h2>
                    </div>
                    <div class="col-sm-6">
                        @can('Add Team Member')
                            <button type="button" class="btn btn-outline-info pull-right" data-toggle="modal" data-target="#myModal1" style="margin-right: 5px">Add Team Member</button>
                        @endcan
                    </div>
                </div>
            </div>
            <div class="row clearfix" id="cardrander">
                <div class="col-lg-12">
                    <div class="card" style="min-height: 500px">
                        @can('View Team Member')
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Skype</th>
                                    <th>Account Manager</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($agents as $k => $agent)
                                    <tr>
                                        <td> {{ ++$k }}</td>
                                        <td>{{ $agent->user->name }}</td>
                                        <td>{{ $agent->user->email }}</td>
                                        <td>{{ $agent->user->mobile }}</td>
                                        <td>{{ $agent->user->skype }}</td>
                                        <td>{{ isset($agent->user->roles[0])? $agent->user->roles[0]->name : 'N/A'}}</td>
                                        <td>
                                            @can('Edit Team Member')
                                                <a href="{{ route('users.edit', $agent->user->id) }}" class="btn btn-info" ><i class="fa fa-edit" aria-hidden="true"></i></a>
                                            @endcan
                                            @can('Delete Team Member')
                                                <button type="button" class="btn btn-danger" onclick="del_team({{ $agent->id }})" ><i class="fa fa-remove" aria-hidden="true"></i></button>
                                            @endcan
                                        </td>
                                    </tr>

                                @endforeach
                                </tbody>
                            </table>
                            @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal1 -->
    <div id="myModal1" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Team Member</h4>
                </div>
                <div class="modal-body">
                    <form class="form-control" action="{{ url('teamMember') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <input type="hidden" name="team_id" value="{{ $teams->id }}">
                        </div>
                        <div class="form-group">
                            <input type="text" name="name" placeholder="Name" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" placeholder="Email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="mobile" placeholder="Phone" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="skype" placeholder="Skype" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="password" placeholder="Password" class="form-control" />
                        </div>
                        <div class='form-group'>
                            @foreach ($roles as $role)
                                {{ Form::radio('roles[]',  $role->id ) }}
                                {{ Form::label($role->name, ucfirst($role->name)) }}<br>

                            @endforeach
                        </div>
                        <br>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-success" value="Submit"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal1 -->
    <div id="getteam" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edit Team</h4>
                </div>
                <div class="modal-body">
                    <form class="form-control" id="team_form" method="post">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <input type="text" id="team_name" name="name" placeholder="Name" class="form-control" />
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-success" value="Submit"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">

        function del_team(id){
            var r = confirm("Are you sure? This might be effect on Tasks!");
            if (r == true) {
                $.ajax({
                    type:'post',
                    url: "{{ url('delteammember/') }}/"+id,
                    data:{
                        '_token':$('input[name=_token]').val()
                    },
                    success:function (data) {
                        toastr.success('Data has been deleted successfully!');
                        location.reload();
                    }
                });
            }
        }

    </script>
@endsection