routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/register', function (){
    return redirect('/login');
});

Route::get('/', function (){
    return redirect('/login');
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', function (){
        return redirect('/task');
    });

    Route::get('home', function (){
        return redirect('/task');
    });

    Route::resource('task','TaskController');

    Route::resource('comment','CommentController');

    Route::resource('media','MediaController');

    Route::delete('mediaDeleteByTask','MediaController@mediaDeleteByTask');

    Route::post('change-status', 'TaskController@changeStatus');

    Route::post('changeTodoStatus', 'TaskController@changeTodoStatus');

//    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('getServiceTeams/{id}', 'ServiceController@getServiceTeams');
    Route::get('show-team-serviecs', 'ServiceController@showTeamAndServices');
    Route::get('deleteTeamServices/{id}', 'ServiceController@deleteTeamServices');
    Route::get('deleteServices/{id}', 'ServiceController@destroy');

    Route::post('storeTeamsServices', 'ServiceController@storeTeamsServices')->name('storeTeamsServices');
    //------------------------------service
    Route::get('addservices','ServiceController@index');
    Route::resource('service',"ServiceController");
//    Route::post('service/{id}','ServiceController@destroy');

//------------------Organization------------------------
    Route::resource('organization','OrganizationController');

    Route::put('organizations/{id}','OrganizationController@update');

    Route::post('delorganization/{id}','OrganizationController@destroy');

    Route::get('getorganization/{id}','OrganizationController@show');
//-----------------------------------------------------------

//------------------Department
    Route::post('department','DepartmentController@store')->name('department');

    Route::post('department/{id}','DepartmentController@destroy');

    Route::get('getdepartment/{id}','DepartmentController@show');

    Route::put('updatedepartment/{id}','DepartmentController@update');

//-------------------------------------------------------------

//------------------Team--------------
    Route::resource('team','TeamController');

    Route::post('delteam/{id}','TeamController@destroy');

    Route::get('getAgentDetail/{id}','TeamController@show');

    Route::put('updateteam/{id}','TeamController@update');

//------------------teamMember
    Route::resource('teamMember','TeamMemberController');

    Route::post('delteammember/{id}','TeamMemberController@destroy');

    Route::get('teamMember/{id}','TeamMemberController@show');

    Route::put('teamMembers/{id}','TeamMemberController@update');

    Route::get('getodep/{id}','DepartmentController@getodep');

    Route::get('getTeamMember/{id}','TeamMemberController@index')->name('getTeamMember');
//-------------------------------------------------------------


    Route::resource('users', 'UserController')->middleware('isAdmin');

    Route::resource('roles', 'RoleController')->middleware('isAdmin');

    Route::resource('permissions', 'PermissionController')->middleware('isAdmin');

//------------------Task Manager
    Route::get('services', function () {
        return view('admin.services.index');
    });

    Route::get('account-manager', function () {
        return view('admin.task-management.account-manager-task-detail');
    });

    Route::resource('type','TypeController');

});

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    protected $fillable = [
        'name',
        'department_id',
        'organization_id',
    ];



    public function department(){
        return $this->belongsTo('App\Department');
    }
    public function teamMembers(){
        return $this->hasMany('App\TeamMember','team_id');
    }
    public function services(){
        return $this->belongsToMany('App\Service');
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use App\Team;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if($user->hasRole('Admin')){
            $teams = Team::all();
        }else{
            $teams = Team::whereId($user->teamMember->team->id)->get();
        }

        $services = Service::all();

        return view('admin.teams.index', compact('teams','services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $team = Team::where('name', $request->name);
        if($request->organization_id && $request->department_id){
            $team = $team->where('organization_id', $request->organization_id)->where('department_id', $request->department_id);
        }
        $team = $team->get();
        if(count($team) > 0){
            toastr()->info('Team name Already Exist!');
            return back();
        }
        $team = Team::create($request->all());
        if($request->services){
            $team->services()->sync($request->services);
        }
        toastr()->success('Data has been Added successfully!');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Team::find($id);
        $output = array(
            'id' => $data->id,
            'name' => $data->name,
        );
        return response()->json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function edit(Team $team)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        Team::findorfail($id)->update($request->all());
        toastr()->success('Data has been Updated successfully!');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Team::destroy($id);
        return back();
    }
}

resources/views/admin/teams/index.blade.php
@extends('admin.layouts.app')

@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-6 col-md-8 col-sm-12">
                        <h2><a href="{{ url()->previous() }}" class="btn btn-xs btn-link"><i
                                        class="fa fa-arrow-left"></i></a>Teams</h2>
                    </div>
                </div>
            </div>
            <div class="row clearfix" id="cardrander">
                <div class="col-lg-12">
                    <div class="card" style="min-height: 500px">
                        <div class="header">
                            <ul class="header-dropdown">
                                <li>
                                    @can('Add Team')
                                        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Team</button>
                                    @endcan
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            @can('View Team')
                                <table class="table table-hover m-b-0 c_list">
                                    <thead>
                                    <tr>
                                        <th>Team Name</th>
                                        <th>Department Name</th>
                                        <th>Organization Name</th>
                                        <th>Created at</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(count($teams))
                                        @foreach($teams as $team)
                                            <tr>
                                                <td><a href="{{ url('getTeamMember/'.$team->id) }}">{{ $team->name }}</a></td>
                                                <td>{{ !is_null($team->department) ?  $team->department->name : '-- -- --' }}</td>
                                                <td>{{ !is_null($team->department) && !is_null($team->department->organization) ? $team->department->organization->name : '-- -- --'}}</td>
                                                <td>{{ !is_null($team->created_at) ? \Carbon\Carbon::parse($team->created_at)->format('h:i A d-m-Y') : '' }}</td>
                                                <td class="text-center">
                                                    @can('Delete Team')
                                                        <form action="{{ route('team.destroy', $team->id) }}" method="post">
                                                            @method('DELETE')
                                                            @csrf
                                                            <button  type="submit" class="btn btn-danger js-sweetalert" title="Delete"><i class="fa fa-trash-o"></i></button>
                                                        </form>
                                                    @endcan
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                    </tbody>
                                </table>
                            @endcan
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal1 -->
    @can('Add Team')
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Team</h4>
                </div>
                <div class="modal-body">
                    <form class="form-control" action="team" method="post">
                        @csrf
                        <div class="form-group">
                            <label class="label">Name*</label>
                            <input type="text" name="name" placeholder="Name" class="form-control" required/>
                        </div>
                        <div class="form-group">
                            <label class="label">Services</label>
                            <div class="row">
                                <div class="col-10">
                                    <select data-placeholder="Choose Services..." id="services" class="chosen-select" tabindex="2" name="services[]" multiple data-height="40px">
                                        <option value="" disabled>Select Services</option>
                                        @foreach($services as $service)
                                            <option value="{{ $service->id }}">{{ $service->title }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-2">
                                    <a href="{{ url('service') }}" class="btn btn-info pull-right" target="_blank" title="Add Services">Add New Services</a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="label">Attach to any organization?</label>
                            <select id="organization_val" name="organization_id" class="form-control" >
                                <option value="" disabled>Select Organization</option>
                                @foreach(App\Organization::all() as $org)
                                    <option value="{{ $org->id }}">{{ $org->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="label">Department</label>
                            <select id="dep_value" name="department_id" class="form-control" ></select>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-success" value="Submit"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @endcan

    <!-- Modal1 -->
    <div id="myModal1" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Team Member</h4>
                </div>
                <div class="modal-body">
                    <form class="form-control" action="teamMember" method="post">
                        @csrf
                        <div class="form-group">
                            <select name="teams_id" class="form-control">
                                <option>Select Team</option>
                                @foreach(App\Team::all() as $team)
                                    <option value="{{ $team->id }}">{{ $team->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" name="name" placeholder="Name" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" placeholder="Email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="mobile" placeholder="Phone" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="skype" placeholder="Skype" class="form-control" />
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <input type="submit" class="btn btn-success" value="Submit"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @endsection
@section('js')

    <script type="text/javascript">
        $(function () {
            $('#organization_val').change(function () {
                var id = $(this).val();
                $.ajax({
                    type: 'get',
                    url: 'getodep/' + id,
                    data: {
                        '_token': $('input[name=_token]').val(),
                    },
                    success: function (data) {
//                        data = JSON.parse(data);
                        $('#dep_value').empty();
                        $('#dep_value').append("<option> Select Department</option>");

                        $.each(data, function(i, item) {
                            $('#dep_value').append("<option value='"+ item.id +"'>"+ item.name+"</option>");
                        });
                    }
                });
            });

        });
    </script>

    @endsection